### ISSUE TITLE
bester nested condition

### ISSUE THREAD

**Issue by moongj** [lovung/decimal#20]
https://github.com/lovung/decimal/blob/0c77a023e558a6d06cd4b8ae4651137720a11b0c/uint64.go#L24

if d1 == 0 && d2 == 0 {
		return 0, 0
	}
	if d1 == 0 && d2 != 0 {
		return -int64(n2), d2
	}
	if d2 == 0 && d1 != 0 {
		return int64(n1), d1
	}
}

should be 
if d1 == 0 {
 if d2 == 0 
return 0, 0
return -int64(n2), d2
}

**Comment by lovung** [comment]
@moongj I think it's not same. We have totally 4 cases

**Comment by lovung** [comment]
Thank you for your contributions. But I will close this issue because of a misunderstanding.
